close all
clear
[Line_list, Line_polygon, polygon_list, meta] = generate_sr_network( ...
    'alpha', 0.7, ...
    'v0', 0.05, ...
    'max_lines', 1000, ...
    'plot_result', true, ...
    'rng_seed', 42, ...
    'save_prefix', '' );

stats = analyze_sr_network(Line_list, meta, ...
    'bins_degree', 20, ...
    'bins_length', 20, ...
    'bins_thickness', 20, ...
    'start_deg_fit', 2, ...
    'start_len_fit', 9, ...
    'start_thk_fit', 1, ...
    'show_figures', true, ...
    'save_plots', true, ...
    'save_prefix', 'run1');